#!/usr/bin/env bash

apt-get -y update

# install aws codedeploy agent
apt-get -y install awscli
apt-get -y install ruby2.0
cd /home/ubuntu
aws s3 cp s3://aws-codedeploy-us-west-2/latest/install . --region us-west-2
chmod +x ./install
./install auto

# install our packages
apt-get -y install nodejs-legacy
apt-get -y install npm
apt-get -y install redis-server