version: 0.0
os: linux
files:
  - source: /
    destination: /opt/twitter-reader
hooks:
  BeforeInstall:
    - location: scripts/aws-codedeploy/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/aws-codedeploy/configure_app
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/aws-codedeploy/start_server
      timeout: 30
      runas: root
  ApplicationStop:
    - location: scripts/aws-codedeploy/stop_server
      timeout: 30
      runas: root